# Numpy

In [1]:
import numpy as np

In [2]:
# Numpy array oluşturma
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [3]:
type(a)

numpy.ndarray

In [4]:
# Array içindeki değerleri 'float' tipine dönüştürür
np.array([4.34, 5, 3, 6], dtype = "float")

array([4.34, 5.  , 3.  , 6.  ])

## Sıfırdan Array Oluşturma
* **zeros**: 0'larla dolu bir array oluşturur
* **ones**:  1'lerle dolu bir array oluşturur
* **full**: Belirtilen değerle dolu array oluşturur
* **arange**: Belirli aralıktaki sayılardan array oluşturur
* **linspace**: Eşit aralıklarla sayılardan array oluşturur
* **random.normal**: Normal dağılımlı rastgele sayılardan array oluşturur
* **random.randint**: Belirtilen aralıktaki rastgele tamsayılardan array oluşturur

In [5]:
np.zeros(5, dtype = int)

array([0, 0, 0, 0, 0])

In [6]:
np.ones((5,2), dtype = int)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [7]:
np.full((2,5), 8)

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

In [8]:
np.arange(1,38,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36])

In [9]:
np.linspace(0,29,15)

array([ 0.        ,  2.07142857,  4.14285714,  6.21428571,  8.28571429,
       10.35714286, 12.42857143, 14.5       , 16.57142857, 18.64285714,
       20.71428571, 22.78571429, 24.85714286, 26.92857143, 29.        ])

In [10]:
np.random.normal(3, 7, (4,3))

array([[ -0.43646617,  -3.25892655,  -9.30966156],
       [  7.28529905, -13.93487441,   9.35468656],
       [ -3.75351971,   4.79854402,  10.82129122],
       [ 13.10455244,  10.81502229,  -0.22761376]])

In [11]:
np.random.randint(0,13, (4,4))

array([[ 5,  5,  6,  9],
       [ 9,  6, 11,  5],
       [ 6,  4,  6,  9],
       [ 3,  7,  4,  4]])

## Özellikleri

* **dytpe**: Tip bilgisini verir
* **ndim**: Boyut sayısını verir
* **shape**: Boyut bilgisini verir
* **size**: Toplam elamam sayısına verir

In [12]:
numArray = np.random.randint(18, size = 16)
numArray

array([ 5, 16,  9,  8,  6,  7,  6, 15,  7,  6, 12,  6,  9,  3,  0,  9])

In [13]:
numArray.dtype

dtype('int32')

In [14]:
numArray.ndim

1

In [15]:
numArray.shape

(16,)

In [16]:
numArray.size

16

In [17]:
numArray2 = np.random.randint(15, size = (4,4))
numArray2

array([[ 9, 10,  5, 14],
       [14,  4, 13, 11],
       [ 6, 10,  9,  8],
       [ 9,  4,  1, 12]])

In [18]:
numArray2.dtype

dtype('int32')

In [19]:
numArray2.ndim

2

In [20]:
numArray.shape

(16,)

In [21]:
numArray.size

16

## Yeniden Şekillendirme (Reshaping)
* Array'in boyutlarını değiştirme işlemidir

In [22]:
npArray = np.array([0,1,2])
npArray2 = np.array([3,4,5])

In [23]:
npArray

array([0, 1, 2])

In [24]:
npArray2

array([3, 4, 5])

In [25]:
np.concatenate([npArray,npArray2])

array([0, 1, 2, 3, 4, 5])

* İki boyut reshaping işlemleri

In [26]:
npArray3 = np.array([[0,1,2,3,4],
                    [5,6,7,8,9]])
npArray3

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [27]:
npArray4 = np.array([[10,11,12,13,14],
                    [15,16,17,18,19]])
npArray4

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [28]:
np.concatenate([npArray3,npArray4])

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [29]:
np.concatenate([npArray3,npArray4], axis = 1)

array([[ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9, 15, 16, 17, 18, 19]])

## Array Ayırma (Splitting)
* Array'i daha küçük parçalara ayırma işlemidir.

In [30]:
numArray = np.random.randint(10, size = 12)
numArray

array([1, 0, 5, 0, 3, 7, 8, 2, 6, 8, 8, 4])

In [31]:
np.split(numArray, [4,9])

[array([1, 0, 5, 0]), array([3, 7, 8, 2, 6]), array([8, 8, 4])]

In [32]:
numArray1, numArray2, numArray3 = np.split(numArray, [4,9])

In [33]:
numArray1

array([1, 0, 5, 0])

In [34]:
numArray2

array([3, 7, 8, 2, 6])

In [35]:
numArray3

array([8, 8, 4])

* İki boyut split işlemleri

In [36]:
m = np.arange(20).reshape(4,5)
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [37]:
np.vsplit(m, [2])

[array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])]

In [38]:
ust, alt = np.vsplit(m, [2])

In [39]:
ust

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [40]:
alt

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [41]:
np.hsplit(m, [2])

[array([[ 0,  1],
        [ 5,  6],
        [10, 11],
        [15, 16]]),
 array([[ 2,  3,  4],
        [ 7,  8,  9],
        [12, 13, 14],
        [17, 18, 19]])]

In [42]:
sag, sol = np.hsplit(m, [2])

In [43]:
sag

array([[ 0,  1],
       [ 5,  6],
       [10, 11],
       [15, 16]])

In [44]:
sol

array([[ 2,  3,  4],
       [ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

## Array Sıralama (Sorting)

In [45]:
numArray = np.array([24,52,12,62,83,20])
numArray

array([24, 52, 12, 62, 83, 20])

In [46]:
np.sort(numArray)

array([12, 20, 24, 52, 62, 83])

* İki boyut reshaping işlemleri

In [47]:
numArray = np.random.randint(1,100, size = (3,3))
numArray

array([[64, 10, 31],
       [13, 27, 96],
       [54, 39, 18]])

In [48]:
np.sort(numArray, axis = 1)

array([[10, 31, 64],
       [13, 27, 96],
       [18, 39, 54]])

In [49]:
np.sort(numArray, axis = 0)

array([[13, 10, 18],
       [54, 27, 31],
       [64, 39, 96]])

## Index ile Elemanlara Erişmek

In [50]:
numArray = np.random.randint(20, size = 20)
numArray

array([17,  1, 10,  8,  9,  5,  5, 15, 14, 15,  5,  6, 12, 10, 13, 10,  1,
       11,  4,  8])

In [51]:
numArray[18]

4

In [52]:
numArray[10]

5

* İki boyut index işlemleri

In [53]:
numArray2 = np.random.randint(10, size = (3,5))
numArray2

array([[9, 7, 4, 3, 9],
       [8, 2, 8, 9, 0],
       [1, 9, 6, 9, 2]])

In [54]:
numArray2[0,2]

4

In [55]:
numArray2[1,3]

9

In [56]:
numArray2[1, 4] = 18

In [57]:
numArray2

array([[ 9,  7,  4,  3,  9],
       [ 8,  2,  8,  9, 18],
       [ 1,  9,  6,  9,  2]])

## Slicing ile Elemanlara Erişmek (Array Alt Kümesine Erişmek)

In [58]:
numArray = np.arange(0,10)
numArray

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
numArray[0:3]

array([0, 1, 2])

In [60]:
numArray[:3]

array([0, 1, 2])

In [61]:
numArray[1::2]

array([1, 3, 5, 7, 9])

In [62]:
numArray[0::3]

array([0, 3, 6, 9])

In [63]:
numArray[0:8:3]

array([0, 3, 6])

* İki boyut slice işlemleri

In [64]:
numArray2 = np.random.randint(1,10, size = (4,4))
numArray2

array([[5, 5, 1, 8],
       [6, 2, 5, 5],
       [9, 5, 3, 1],
       [8, 6, 5, 4]])

In [65]:
numArray2[:,0]

array([5, 6, 9, 8])

In [66]:
numArray2[:,2]

array([1, 5, 3, 5])

In [67]:
numArray2[1:,]

array([[6, 2, 5, 5],
       [9, 5, 3, 1],
       [8, 6, 5, 4]])

In [68]:
numArray2[0:4, 1:4]

array([[5, 1, 8],
       [2, 5, 5],
       [5, 3, 1],
       [6, 5, 4]])

In [69]:
numArray2[1:2,]

array([[6, 2, 5, 5]])

## Fancy Index ile Elemanlara Erişmek

In [70]:
numArray = np.arange(10,101, 10)
numArray

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [71]:
numArray1, numArray2, numArray3 = [ numArray[2], numArray[5], numArray[0] ]

In [72]:
numArray1

30

In [73]:
numArray2

60

In [74]:
numArray3

10

* iki boyutta fancy

In [75]:
numArray2 = np.random.randint(1,19, size = 9).reshape(3,3)
numArray2

array([[ 2, 17, 16],
       [11,  8, 14],
       [ 8,  2,  4]])

In [76]:
satir = np.array(numArray2[0,1])
sutun = np.array(numArray2[1,2])

In [77]:
satir

array(17)

In [78]:
sutun

array(14)

In [79]:
numArray2[1, [0,1]]

array([11,  8])

## Koşullu Eleman İşlemleri

In [80]:
numArray = np.random.randint(0,20, size = 9)
numArray

array([10,  1,  9, 16,  3, 18, 16, 18,  5])

In [81]:
numArray > 10

array([False, False, False,  True, False,  True,  True,  True, False])

In [82]:
numArray[numArray > 5]

array([10,  9, 16, 18, 16, 18])

In [83]:
numArray[ numArray == 15]

array([], dtype=int32)

In [84]:
numArray * 3

array([30,  3, 27, 48,  9, 54, 48, 54, 15])

In [85]:
numArray / 100

array([0.1 , 0.01, 0.09, 0.16, 0.03, 0.18, 0.16, 0.18, 0.05])

In [86]:
numArray * 20/ 12+ 39 -84

array([-28.33333333, -43.33333333, -30.        , -18.33333333,
       -40.        , -15.        , -18.33333333, -15.        ,
       -36.66666667])

## Matematiksel İşlemler

In [87]:
numArray = np.arange(1,15)
numArray

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [88]:
np.subtract(numArray, 10)

array([-9, -8, -7, -6, -5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [89]:
np.add(numArray, 10)

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [90]:
np.multiply(numArray, 10)

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
       140])

In [91]:
np.divide(numArray, 10)

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2, 1.3,
       1.4])

In [92]:
np.power(numArray, 2)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196], dtype=int32)

In [93]:
np.mod(numArray, 2)

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0], dtype=int32)

In [94]:
np.log(numArray)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733])

In [95]:
np.mean(numArray)

7.5

In [96]:
np.sum(numArray)

105

In [97]:
np.min(numArray)

1

In [98]:
np.max(numArray)

14