# Pandas

In [1]:
import pandas as pd 

In [2]:
pdSeri = pd.Series([12,35,58,43,53])
pdSeri

0    12
1    35
2    58
3    43
4    53
dtype: int64

In [3]:
pdSeri.dtype

dtype('int64')

In [4]:
pdSeri.size

5

In [5]:
pdSeri.ndim

1

In [6]:
pdSeri.head(2)

0    12
1    35
dtype: int64

In [7]:
pdSeri.tail(4)

1    35
2    58
3    43
4    53
dtype: int64

### index isimlendirmesi

In [8]:
pdSeri = pd.Series([85,92,70,63,46], index = ["Ali","Mehmet","Ceyda","Elif","Furkan"])
pdSeri

Ali       85
Mehmet    92
Ceyda     70
Elif      63
Furkan    46
dtype: int64

In [9]:
pdSeri["Ali"]

85

In [10]:
pdSeri["Elif"]

63

### Sozluk uzerinden liste olusturmak

In [11]:
sozluk = {"Ali":85, "Furkan":46, "Elif": 63}
pdSeri = pd.Series(sozluk)
pdSeri

Ali       85
Furkan    46
Elif      63
dtype: int64

In [12]:
pd.concat([pdSeri,pdSeri])

Ali       85
Furkan    46
Elif      63
Ali       85
Furkan    46
Elif      63
dtype: int64

### Eleman İşlemleri

In [13]:
import numpy as np

numArray = np.random.randint(1,100, size = 10)
pdSeri = pd.Series(numArray)
pdSeri

0    59
1    34
2    64
3    77
4    64
5    53
6     6
7    95
8    41
9    10
dtype: int32

In [14]:
pdSeri[3:8]

3    77
4    64
5    53
6     6
7    95
dtype: int32

In [15]:
pdSeri.index

RangeIndex(start=0, stop=10, step=1)

In [16]:
pdSeri.keys

<bound method Series.keys of 0    59
1    34
2    64
3    77
4    64
5    53
6     6
7    95
8    41
9    10
dtype: int32>

In [17]:
pdSeri.values

array([59, 34, 64, 77, 64, 53,  6, 95, 41, 10])

In [18]:
4 in pdSeri

True

In [19]:
39 in pdSeri

False

# Pandas DataFrame Oluşturma

In [20]:
list = [81,64,39,75,93]
pdData = pd.DataFrame(list)
pdData

0
0  81
1  64
2  39
3  75
4  93

In [21]:
pd.DataFrame(data = list, columns = ["Sınav Notları"])

Sınav Notları
0             81
1             64
2             39
3             75
4             93

In [22]:
numArray = np.random.randint(1,100, size = (4,4))
numArray

array([[62, 91, 70, 45],
       [16, 81, 50, 20],
       [13, 97,  8, 76],
       [59, 91, 18, 46]])

In [23]:
pdData2 = pd.DataFrame(data = numArray, columns = ["quiz 1","quiz 2","Arasınav","Final"])
pdData2

quiz 1  quiz 2  Arasınav  Final
0      62      91        70     45
1      16      81        50     20
2      13      97         8     76
3      59      91        18     46

In [24]:
pdData2.axes

[RangeIndex(start=0, stop=4, step=1),
 Index(['quiz 1', 'quiz 2', 'Arasınav', 'Final'], dtype='object')]

In [25]:
pdData2.shape

(4, 4)

In [26]:
pdData2.values

array([[62, 91, 70, 45],
       [16, 81, 50, 20],
       [13, 97,  8, 76],
       [59, 91, 18, 46]])

In [27]:
pdData2.head(2)

quiz 1  quiz 2  Arasınav  Final
0      62      91        70     45
1      16      81        50     20

In [28]:
pdData2.tail(3)

quiz 1  quiz 2  Arasınav  Final
1      16      81        50     20
2      13      97         8     76
3      59      91        18     46

In [29]:
pdData2

quiz 1  quiz 2  Arasınav  Final
0      62      91        70     45
1      16      81        50     20
2      13      97         8     76
3      59      91        18     46

In [30]:
# Eğer kesin silinmesini istenilirse inplace = True ifadesi kullanılır
pdData2.drop("Arasınav", axis = 1)

quiz 1  quiz 2  Final
0      62      91     45
1      16      81     20
2      13      97     76
3      59      91     46

In [31]:
pdData2

quiz 1  quiz 2  Arasınav  Final
0      62      91        70     45
1      16      81        50     20
2      13      97         8     76
3      59      91        18     46

In [32]:
pdData2.drop("Arasınav", axis = 1, inplace = True)

In [33]:
# Görüldüğü üzere artık pdData2 çağırıldığında Arasınav sütunu gözükmeyecektir
pdData2

quiz 1  quiz 2  Final
0      62      91     45
1      16      81     20
2      13      97     76
3      59      91     46

### loc & iloc

In [34]:
numArray = np.random.randint(1,100, size = (7,4))
pdData = pd.DataFrame(data = numArray , columns = ["quiz1","quiz2","Arasınav","Final"])
pdData

quiz1  quiz2  Arasınav  Final
0     23     45        64     49
1     24     75        92     68
2     72     28         2     17
3     55     34        87     50
4     78     15        26     90
5     65     12        79     56
6     67     94         1     96

In [35]:
#loc: Tanımlandığı şekli ile seçer.
pdData.loc[1:4]

quiz1  quiz2  Arasınav  Final
1     24     75        92     68
2     72     28         2     17
3     55     34        87     50
4     78     15        26     90

In [36]:
#iloc: İndeksleme mantığı ile seçer.
pdData.iloc[1:4]

quiz1  quiz2  Arasınav  Final
1     24     75        92     68
2     72     28         2     17
3     55     34        87     50

In [37]:
pdData.loc[1:4, "Arasınav"]

1    92
2     2
3    87
4    26
Name: Arasınav, dtype: int32

In [38]:
pdData.loc[1:4]["Arasınav"]

1    92
2     2
3    87
4    26
Name: Arasınav, dtype: int32

### Koşullu Eleman İşlemleri

In [39]:
numArray = np.random.randint(1,100, size = (7,4))
pdData = pd.DataFrame(data = numArray , columns = ["quiz1","quiz2","Arasınav","Final"])
pdData

quiz1  quiz2  Arasınav  Final
0     33     52        31     24
1     53     80         4     84
2     18     92        96     58
3      1     49        71     13
4     53     30        97     13
5     47     43        60     98
6      6     13        13     32

In [40]:
pdData[pdData.Final > 20]

quiz1  quiz2  Arasınav  Final
0     33     52        31     24
1     53     80         4     84
2     18     92        96     58
5     47     43        60     98
6      6     13        13     32

In [41]:
pdData[(pdData.Final > 15) & (pdData.Arasınav < 5)]

quiz1  quiz2  Arasınav  Final
1     53     80         4     84

In [42]:
pdData.loc[(pdData.Final > 15) , ["quiz1","quiz2"]]

quiz1  quiz2
0     33     52
1     53     80
2     18     92
5     47     43
6      6     13

### Birleştirme (Join) İşlemleri

In [43]:
numArray = np.random.randint(1,100, size = (7,4))
pdData = pd.DataFrame(data = numArray , columns = ["quiz1","quiz2","Arasınav","Final"])
pdData

quiz1  quiz2  Arasınav  Final
0     23     88        19     19
1     96     38        29     92
2     33     97        11     90
3     66     48        64     33
4     49     75        85     31
5     98     38         7     11
6     77     14        28     82

In [44]:
pdData2 = pdData + 19
pdData2

quiz1  quiz2  Arasınav  Final
0     42    107        38     38
1    115     57        48    111
2     52    116        30    109
3     85     67        83     52
4     68     94       104     50
5    117     57        26     30
6     96     33        47    101

In [45]:
pd.concat([pdData,pdData2])

quiz1  quiz2  Arasınav  Final
0     23     88        19     19
1     96     38        29     92
2     33     97        11     90
3     66     48        64     33
4     49     75        85     31
5     98     38         7     11
6     77     14        28     82
0     42    107        38     38
1    115     57        48    111
2     52    116        30    109
3     85     67        83     52
4     68     94       104     50
5    117     57        26     30
6     96     33        47    101

In [46]:
pd.concat([pdData,pdData2], ignore_index = True)

quiz1  quiz2  Arasınav  Final
0      23     88        19     19
1      96     38        29     92
2      33     97        11     90
3      66     48        64     33
4      49     75        85     31
5      98     38         7     11
6      77     14        28     82
7      42    107        38     38
8     115     57        48    111
9      52    116        30    109
10     85     67        83     52
11     68     94       104     50
12    117     57        26     30
13     96     33        47    101

In [47]:
pdData2.columns = ["quiz1","q2","ara","fin"]

In [48]:
pdData2

quiz1   q2  ara  fin
0     42  107   38   38
1    115   57   48  111
2     52  116   30  109
3     85   67   83   52
4     68   94  104   50
5    117   57   26   30
6     96   33   47  101

In [49]:
pd.concat([pdData,pdData2])

quiz1  quiz2  Arasınav  Final     q2    ara    fin
0     23   88.0      19.0   19.0    NaN    NaN    NaN
1     96   38.0      29.0   92.0    NaN    NaN    NaN
2     33   97.0      11.0   90.0    NaN    NaN    NaN
3     66   48.0      64.0   33.0    NaN    NaN    NaN
4     49   75.0      85.0   31.0    NaN    NaN    NaN
5     98   38.0       7.0   11.0    NaN    NaN    NaN
6     77   14.0      28.0   82.0    NaN    NaN    NaN
0     42    NaN       NaN    NaN  107.0   38.0   38.0
1    115    NaN       NaN    NaN   57.0   48.0  111.0
2     52    NaN       NaN    NaN  116.0   30.0  109.0
3     85    NaN       NaN    NaN   67.0   83.0   52.0
4     68    NaN       NaN    NaN   94.0  104.0   50.0
5    117    NaN       NaN    NaN   57.0   26.0   30.0
6     96    NaN       NaN    NaN   33.0   47.0  101.0

In [50]:
pd.concat([pdData,pdData2], join = "inner")

quiz1
0     23
1     96
2     33
3     66
4     49
5     98
6     77
0     42
1    115
2     52
3     85
4     68
5    117
6     96

In [51]:
sozluk = { "Çalışanlar": ["Mehmet","Ali","Elif","Furkan"],
            "Departman": ["Veri Bilimi","Mobil Uygulama","Web Geliştirme","Backend"]} 
sozluk

{'Çalışanlar': ['Mehmet', 'Ali', 'Elif', 'Furkan'],
 'Departman': ['Veri Bilimi', 'Mobil Uygulama', 'Web Geliştirme', 'Backend']}

In [52]:
pdData3 = pd.DataFrame(sozluk)
pdData3

Çalışanlar       Departman
0     Mehmet     Veri Bilimi
1        Ali  Mobil Uygulama
2       Elif  Web Geliştirme
3     Furkan         Backend

In [53]:
sozluk2 = { "Çalışanlar": ["Mehmet","Ali","Elif","Furkan"],
            "İşe_Giriş_Tarihi": [2022,2019,2024,2010]}
sozluk2

{'Çalışanlar': ['Mehmet', 'Ali', 'Elif', 'Furkan'],
 'İşe_Giriş_Tarihi': [2022, 2019, 2024, 2010]}

In [54]:
pdData4 = pd.DataFrame(sozluk2)
pdData4

Çalışanlar  İşe_Giriş_Tarihi
0     Mehmet              2022
1        Ali              2019
2       Elif              2024
3     Furkan              2010

In [55]:
pd.merge(pdData3,pdData4)

Çalışanlar       Departman  İşe_Giriş_Tarihi
0     Mehmet     Veri Bilimi              2022
1        Ali  Mobil Uygulama              2019
2       Elif  Web Geliştirme              2024
3     Furkan         Backend              2010

### Gruplama İşlemleri

In [56]:
pdData = pd.DataFrame(
                     {'Grup': ['A', 'B', 'C', 'A', 'B', 'C'],
                      'Aldığı_Puan': [7,5,8,9,4,6]}, 
                      columns=['Grup', 'Aldığı_Puan'])

pdData

Grup  Aldığı_Puan
0    A            7
1    B            5
2    C            8
3    A            9
4    B            4
5    C            6

In [57]:
pdData.groupby("Grup").mean()

Aldığı_Puan
Grup             
A             8.0
B             4.5
C             7.0

In [58]:
pdData.groupby("Grup").sum()

Aldığı_Puan
Grup             
A              16
B               9
C              14

In [59]:
pdData.groupby("Grup").sum()

Aldığı_Puan
Grup             
A              16
B               9
C              14

In [60]:
pdData.describe().T

count  mean       std  min   25%  50%   75%  max
Aldığı_Puan    6.0   6.5  1.870829  4.0  5.25  6.5  7.75  9.0